### ISSUE TITLE
Default OpenSearch policy for "other" only seems to preserve logs for 5 days

### ISSUE THREAD

**Issue by wvh** [elastisys/compliantkubernetes-apps#1006]
**Describe the bug**
The default OpenSearch configuration only preserves log index for 5 days at an average Kubernetes cluster logging rate. This is not enough for a comprehensive log retention period.

Somewhat related: there is no documentation on best practices how to override default logging policies without risking them to be overridden by future compliantkubernetes-apps updates.

**To Reproduce**
- install apps with default settings
- explore "other" index for cluster logs

**Expected behavior**
- One would expect logs to persist for at least 7, perhaps 14 days by default.
- Some documentation how how Elastisys wants users to override defaults set by its helm(file).

**Screenshots**
No screenshots.

**Version (add all relevant versions):**
 - Compliant kubernetes apps version [e.g. v0.8.0]

**Additional context**
Log retention and index configuration defaults seem insufficient for a normative workload cluster's output.

I'm filing this as a bug report because I think the defaults should cover regular use cases. This could also be classified as a feature request or documentation issue instead.

**Comment by OlleLarsson** [comment]
Hi @wvh, thank you for opening this issue.
We are indeed lacking in documentation in this area.
In order to change the retention for indices in OpenSearch you need to override the defaults config by putting the `opensearch.curator.retention` in your `CK8S_CONFIG_PATH/sc-config.yaml` file, e.g.
```yaml
opensearch:
 ...
  curator:
    retention:
      - pattern: other-*
        sizeGB: 5
        ageDays: 30
      - pattern: kubeaudit-*
        sizeGB: 200
        ageDays: 30
      - pattern: kubernetes-*
        sizeGB: 1000
        ageDays: 30
      - pattern: authlog-*
        sizeGB: 1
        ageDays: 30
      - pattern: security-auditlog-*
        sizeGB: 1
        ageDays: 30
      - pattern: my-other-pattern*
        sizeGB: 123
        ageDays: 123
```
Note that you need to include all the patterns that you desire to have retention for as it the list in the override config does not merge with the defaults.
