### ISSUE TITLE
Upstream More falco rules 

### ISSUE THREAD

**Issue by raviranjanelastisys** [elastisys/compliantkubernetes-apps#1355]
**What should be investigated.**
Investigate if there  is more opportunity to upstream OK alerts or known behavior of Falco because it seems like we need to add few more images to whitelist the known behavior . You can refer PR - https://github.com/falcosecurity/falco/pull/1981/files

```
  - source: "pod"
    name: "Launch Package Management Process in Container"
    details:
      host: node
      proc.cmdline: gem /usr/local/bin/gem contents fluent-plugin-opensearch
    why_ok: "Expected behavior: Fluentd needs to download plugin on start"

  - source: "pod"
    name: "Contact K8S API Server From Container"
    details:
      host: node
      container.image.repository: registry.opensource.zalan.do/acid/spilo-14
      container.image.tag: 2.1-p3
      proc.cmdline: 'patroni /usr/local/bin/patroni /home/postgres/postgres.yml'
    why_ok: "Expected behavior: Patroni talks to the API server at times"
```

**What artifacts should this produce.**
Upstream the falco rules
