### ISSUE TITLE
OpenSearch - Missing object storage in configurer network policy

### ISSUE THREAD

**Issue by Elias-elastisys** [elastisys/compliantkubernetes-apps#1410]
**Describe the bug**
During a clean install of the service cluster apps v0.28.0, the OpenSearch configurer was unable to access the s3 storage. After we removed all network policies in the opensearch namespace it finally succeeded.

**To Reproduce**
1. Have a service cluster without any apps.
2. Run `bin/ck8s apply sc`
3. It should get stuck at the opensearch-configurer

**Expected behavior**
The configurer should be able to access s3 storage and succeed. 

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.28.0

**Additional context**
Looking into the policies, it seems as if the [policy targeting the configurer](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/networkpolicy-service/templates/opensearch/configurer.yaml) does not have the object storage config. 

It seems as if object storage is only configured in [master.yaml](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/networkpolicy-service/templates/opensearch/master.yaml) which does not select the configurer.

**Comment by aarnq** [comment]
Hi Elias, I'm pretty sure that there shouldn't be an issue that configurer can't talk to object store since it shouldn't talk to that on it's own it is done via the OpenSearch masters. [See script for reference.](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/opensearch/configurer/files/configurer.sh)

Though did this continue for a long time? Since (in personal experience) netpols can take time to apply if you have as many as we do in apps. Did you get any log output from the configurer that could point us to the right direction?

**Comment by Elias-elastisys** [comment]
Hi, as I looked into the logs now it seems as if both a master, a data and the configurer logged the same type of error:

`Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to [ip-hidden] failed: Connect timed out`

We have had issues with s3 access from opensearch for a few days but was successful today which seemed to be when we removed the netpols, the configurer never managed to complete before.

**Comment by aarnq** [comment]
Alright that makes more sense. I have some follow up questions:
What type of cloud are you running on? Is it AWS, Exoscale, OpenStack, UpCloud, bare metal or other?
Have you used the `update-ips` script to set the IPs and ports, and can you verify that:
```bash
./bin/ck8s ops helmfile sc -l app=service-cluster-np template | yq4 'select(.metadata.name == "allow-opensearch-master")'
```
contains the object store IPs and ports you've set?

**Comment by Elias-elastisys** [comment]
This is an on-prem project, running on Videnca, I think we selected baremetal when initializing. They provided us with an s3 endpoint on port 8082. While troubleshooting we skipped `update-ips` and simply allowed every ip:

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-opensearch-master
  namespace: opensearch-system
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/component: opensearch-master
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: opensearch-curator
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: opensearch-backup
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: opensearch-slm
        - podSelector:
            matchLabels:
              app: opensearch-dashboards
        - podSelector:
            matchLabels:
              app: prometheus-elasticsearch-exporter
        - podSelector:
            matchLabels:
              app: configurer
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: opensearch-securityadmin
      ports:
        - port: 9200
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: opensearch-master
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: opensearch-data
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: opensearch-client
      ports:
        - port: 9300
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: opensearch-master
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: opensearch-data
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: opensearch-client
      ports:
        - port: 9300
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: dex
              app.kubernetes.io/instance: dex
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: dex
      ports:
        - port: 5556
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 8082
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
    - ports:
        - port: 53
          protocol: UDP
```
