### ISSUE TITLE
Create user for elasticdump by default

### ISSUE THREAD

**Issue by davidumea** [elastisys/compliantkubernetes-apps#1476]
**Is your feature request related to a problem? Please describe.**
As it is a semi-popular request to be able to export logs from Opensearch, we often recommend to use Elasticdump. Currently this requires the cluster admins to create a special Opensearch user for the users. It would be nice if the Opensearch user already existed so users of CK8S can just follow [this page](https://elastisys.io/compliantkubernetes/user-guide/long-term-log-retention/#exporting-indices) on our public docs to export logs.

**Describe the solution you'd like**
Create a user called e.g. "log_exporter" or "elasticdump" that has these permissions:

```yaml
    - role_name: log_exporter
      definition:
        cluster_permissions:
          - cluster_monitor
          - indices:data/read/scroll
          - indices:data/read/scroll/clear
        index_permissions:
          - index_patterns:
              - '*'
            allowed_actions:
              - indices:admin/aliases/get
              - indices:monitor/*
          - index_patterns:
            {{- if .Values.opensearch.indexPerNamespace }}
            - '/^(?!kube-system|gatekeeper-system|other|authlog|\.).*/'
            {{- else }}
            - "kubernetes-*"
            - "kubeaudit-*"
            {{- end }}
            allowed_actions:
              - read
              - search
             - indices_monitor
              - indices:admin/mappings/get
              - indices:admin/get
```

The users password could be stored in a secret in the cluster, then the user admins also need the required permissions to get this secret.

Also update the public documentation and let the users know the users name and how to get hold of the user password.

**Definition of done:**
There is now a user set up by configurer that can be used for exporting logs.
