### ISSUE TITLE
Falco customRules creates an error during bin/ck8s init

### ISSUE THREAD

**Issue by robinAwallace** [elastisys/compliantkubernetes-apps#1505]
**Describe the bug**

When adding a customRule file for falco to one of the config the init prints an error during the updating of the config.

**To Reproduce**
1. Add a customRules file to wc-config.yaml
	```yaml
	falco:
	  customRules:
	    test.yaml: |-
	      - macro: user_known_non_sudo_setuid_conditions
	        condition: (
	            user.name=root
	            )
	```
2. Run `./bin/ck8s init`
3. See that `Updating wc config` prints an error
	```bash
	[ck8s] Updating wc config
	Error: cannot index array with 'test.yaml' (strconv.ParseInt: parsing "test.yaml": invalid syntax)
	```

**Expected behavior**

Expecting it to be able to handle customRules with extra files. 

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version [v0.28.1]

**Additional context**
