### ISSUE TITLE
Netpol should allow ceph-crashcollector to mon and mgr

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#1794]
**Describe the bug**:

When the crashcollector finds crash reports it sends them to mgr I think, but it seems to auth via the mons so it needs access to both.

**To Reproduce**:

Steps to reproduce the behaviour:

1. Have a ceph pod crash
1. See blocked packets from crashcollector

**Expected behaviour**:

Crash report should come to the ceph cluster.

**Version (add all relevant versions)**:

- Compliant Kubernetes apps version v0.32

**Additional context**:

This also needs to be fixed in the kubespray repo before it is considered done.

**Comment by crssnd** [comment]
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-rook-ceph-crashcollector
  namespace: rook-ceph
spec:
  egress:
  - ports:
    - endPort: 7300
      port: 6800
      protocol: TCP
    - port: 9283
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: rook-ceph-mgr
  - ports:
    - port: 6789
      protocol: TCP
    - port: 3300
      protocol: TCP
    - port: 7000
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: rook-ceph-mon
  podSelector:
    matchLabels:
      app: rook-ceph-crashcollector
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-rook-ceph-mgr-from-crashcollector
  namespace: rook-ceph
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: rook-ceph-crashcollector
  - ports:
    - endPort: 7300
      port: 6800
      protocol: TCP
    - port: 9283
      protocol: TCP
  podSelector:
    matchLabels:
      app: rook-ceph-mgr
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-rook-ceph-mon-from-crashcollector
  namespace: rook-ceph
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: rook-ceph-crashcollector
    ports:
    - port: 6789
      protocol: TCP
    - port: 3300
      protocol: TCP
    - port: 7000
      protocol: TCP
  podSelector:
    matchLabels:
      app: rook-ceph-mon
  policyTypes:
  - Ingress
```
