### ISSUE TITLE
Better support direct routed ingress in network policies

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#1972]
### Description

Currently with direct routed ingress traffic we set the following:
```yaml
networkPolicies:
  ingressNginx:
    ingressOverride:
      enabled: true
      ips:
        - 0.0.0.0/0
```
Since the IP Ingress-NGINX see is the actual IP of the client, and we should support this in a manner that is more of a _normal procedure_ rather than something that looks like an exception.

### Additional context

I propose that we add a config option `ingressUsingDirectRouting` to enable this instead and keep the `ingressOverride` as an exception.

### Definition of done

- [ ] Support direct routing as an ingress type in network policies.
