### ISSUE TITLE
Interactions between falco.enabled and falco.falcoSidekick values

### ISSUE THREAD

**Issue by jakubkrzywda** [elastisys/compliantkubernetes-apps#259]
**Describe the bug**
Issues when installing workload cluster caused by the interactions between `falco.enabled` and `falco.falcoSidekick` values.

When `falco.enabled` is set to false, still the `falco.falcoSidekick` values are mandatory:

```
[ck8s] Validating wc config
[ck8s] WARN: nfsProvisioner.server is not set in /home/runner/work/k8s-compliant-kubernetes/k8s-compliant-kubernetes/compliant-k8s-icap-server-pipeline/wc-config.yaml
[ck8s] WARN: nfsProvisioner.path is not set in /home/runner/work/k8s-compliant-kubernetes/k8s-compliant-kubernetes/compliant-k8s-icap-server-pipeline/wc-config.yaml
[ck8s] WARN: user.createNamespaces is not set in /home/runner/work/k8s-compliant-kubernetes/k8s-compliant-kubernetes/compliant-k8s-icap-server-pipeline/wc-config.yaml
[ck8s] WARN: falco.falcoSidekick.resources.limits.cpu is not set in /home/runner/work/k8s-compliant-kubernetes/k8s-compliant-kubernetes/compliant-k8s-icap-server-pipeline/wc-config.yaml
[ck8s] WARN: falco.falcoSidekick.resources.limits.memory is not set in /home/runner/work/k8s-compliant-kubernetes/k8s-compliant-kubernetes/compliant-k8s-icap-server-pipeline/wc-config.yaml
[ck8s] WARN: falco.falcoSidekick.resources.requests.cpu is not set in /home/runner/work/k8s-compliant-kubernetes/k8s-compliant-kubernetes/compliant-k8s-icap-server-pipeline/wc-config.yaml
[ck8s] WARN: falco.falcoSidekick.resources.requests.memory is not set in /home/runner/work/k8s-compliant-kubernetes/k8s-compliant-kubernetes/compliant-k8s-icap-server-pipeline/wc-config.yaml
[ck8s] WARN: falco.falcoSidekick.tolerations is not set in /home/runner/work/k8s-compliant-kubernetes/k8s-compliant-kubernetes/compliant-k8s-icap-server-pipeline/wc-config.yaml
[ck8s] WARN: falco.falcoSidekick.affinity is not set in /home/runner/work/k8s-compliant-kubernetes/k8s-compliant-kubernetes/compliant-k8s-icap-server-pipeline/wc-config.yaml
[ck8s] WARN: falco.falcoSidekick.nodeSelector is not set in /home/runner/work/k8s-compliant-kubernetes/k8s-compliant-kubernetes/compliant-k8s-icap-server-pipeline/wc-config.yaml
[ck8s] Do you want to abort? (y/n):
Provisioning step had errors: Running the cleanup provisioner, if present...
Terminating the source AWS instance...
Cleaning up any extra volumes...
No volumes to clean up, skipping
```

However, if I set `falco.falcoSidekick` values, I get the following error:

```
FAILED RELEASES:
NAME
falcosidekick
in ./01-applications.yaml: failed processing release falcosidekick: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: upgrade (7 bytes)
  2: --install (9 bytes)
  3: --reset-values (14 bytes)
  4: falcosidekick (13 bytes)
  5: charts/falcosidekick (20 bytes)
  6: --version (9 bytes)
  7: 0.1.14 (6 bytes)
  8: --timeout (9 bytes)
  9: 600s (4 bytes)
  10: --namespace (11 bytes)
  11: falco (5 bytes)
  12: --values (8 bytes)
  13: /tmp/values907527766 (20 bytes)
  14: --history-max (13 bytes)
  15: 10 (2 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: create: failed to create: namespaces "falco" not found

COMBINED OUTPUT:
  Release "falcosidekick" does not exist. Installing it now.
  Error: create: failed to create: namespaces "falco" not found
exit status 1
``` 

**To Reproduce**
To reproduce the behavior run `./bin/ck8s apply wc` with the following `falco` config:

```
falco:
    enabled: false
    resources:
        limits:
            cpu: 200m
            memory: 1024Mi
        requests:
            cpu: 100m
            memory: 512Mi
    tolerations:
    -   key: node-role.kubernetes.io/master
        effect: NoSchedule
    affinity: {}
    nodeSelector: {}
    alerts:
        enabled: true
        # supported: alertmanager|slack
        type: alertmanager
        priority: notice
        hostPort: http://kube-prometheus-stack-alertmanager.monitoring:9093
        # if type=slack falco.alerts.slackWebhook must be set in the secrets yaml file
    falcoSidekick:
        resources:
            limits:
                cpu: 20m
                memory: 50Mi
            requests:
                cpu: 10m
                memory: 25Mi

        tolerations: []
        affinity: {}
        nodeSelector: {}
```

**Expected behavior**
When `falco.enabled` is set to `false` I would expect the `falcoSidekick` values not to be mandatory.

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.10.0

**Additional context**
