### ISSUE TITLE
InfluxDB secrets specified in multiple places

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#412]
**Is your feature request related to a problem? Please describe.**
The passwords for InfluxDB are stored in the `secrets.yaml` file under `influxDB.users` and `prometheus.remoteWrite`. Obviously, the password for remote write must match one of the InfluxDB user passwords to make things work, but this is not mentioned anywhere and there is no explanation for these fields. (Comments in the secret "templates" are stripped.)

```yaml
influxDB:
  users:
    adminPassword: somelongsecret
    wcWriterPassword: somelongsecret
    scWriterPassword: somelongsecret
...
prometheus:
  remoteWrite:
    # Same as the password for the 'influxDB.users.wcWrtier' user in 'sc-config.yaml'.
    password: somelongsecret
```

**Describe the solution you'd like**
The password(s) for remote write should not be duplicated (if possible). And in either case it should be made clear what each password is supposed to be used for.

**Describe alternatives you've considered**
Keep duplicate copies of the passwords (e.g. `sc-secrets.yaml` and `wc-secrets.yaml` to match the current `sc-config.yaml` and `wc-config.yaml`) to make multiple WCs easier. In this case it would be helpful to use the same field in each file to make it obvious what should match. For example, store the password at `influxDB.users.remoteWrite.password` in both `sc-secrets.yaml` and `wc-secrets.yaml` instead of using `prometheus.remoteWrite.password` in `wc-secrets.yaml`.

**Additional context**

**Definition of done:**
InfluxDB passwords are not duplicated in `secrets.yaml` and/or these fields are well described so it is easy to understand if two fields must match.
