### ISSUE TITLE
[3] Common-config

### ISSUE THREAD

**Issue by robinAwallace** [elastisys/compliantkubernetes-apps#602]
**Is your feature request related to a problem? Please describe.**

There are multiple variables in sc/wc-config that are "common" (you have to write the same in both config files). This can lead to misconfiguration between the config files. Also the documentation is more clear in the wc-config then in the sc-config. This would solve some of the confusion, especially for new members. 

**Describe the solution you'd like**

I suggests that there should be a common configuration which is used when installing apps.

**Describe alternatives you've considered**

The other alternative is to keep it as it is.

**Additional context**
From sc-config:
```yaml
global:
  ## Compliantkubernetes-apps version.
  ## Use version number if you are exactly at a release tag.
  ## Otherwise use full commit hash of current commit.
  ## 'any', can be used to disable this validation.
  ck8sVersion: ${CK8S_VERSION}
  clusterName: ${CK8S_ENVIRONMENT_NAME}-sc
  baseDomain: set-me
  opsDomain: set-me
  issuer: letsencrypt-staging
  verifyTls: true
  clusterDns: 10.233.0.3
```
From wc-config:
```yaml
## Some common options used in various helm charts.
##
global:
  ## Compliantkubernetes-apps version.
  ## Use version number if you are exactly at a release tag.
  ## Otherwise use full commit hash of current commit.
  ## 'any', can be used to disable this validation.
  ck8sVersion: ${CK8S_VERSION}
  ## The cluster name.
  ## Used in logs and metrics as to separate these from other clusters.
  clusterName: ${CK8S_ENVIRONMENT_NAME}-wc
  ## Domain intended for ingress usage in the workload cluster
  ## and to reach user facing services such as kibana, grafana, and harbor.
  ## E.g. with 'prod.domain.com', kibana is reached via 'kibana.prod.domain.com'.
  baseDomain: set-me
  ## Domain intended for ingress usage in the service cluster and to reach
  ## non-user facing services such as influxdb and elasticsearch.
  ## E.g. with 'ops.prod.domain.com', elasticsearch is reached via 'elastic.ops.prod.domain.com'.
  opsDomain: set-me
  ## Default cert-manager issuer to use for issuing certificates for ingresses.
  ## Normally one of 'letsencrypt-staging' or 'letsencrypt-prod'.
  issuer: letsencrypt-staging
  ## Verify ingress certificates
  verifyTls: true
  ## IP of the cluster DNS in kubernetes
  clusterDns: 10.233.0.3
```

Both set of variables need to be set to the same.

**Definition of done:**
When could this feature be considered done.

* I can configure common attributes from a common-config file.
