### ISSUE TITLE
[3]Add the ability to use repository caches

### ISSUE THREAD

**Issue by rjonsson** [elastisys/compliantkubernetes-apps#643]
**Is your feature request related to a problem? Please describe.**
On our bare-metal install we have a problem with rate-limiting from dockerhub with the same outgoing IP as alot of other server, of which we have no control.

**Describe the solution you'd like**
Add an variable to the cluster-configurations and modifying the templates for the value-files

**Describe alternatives you've considered**
Modifying /etc/docker/config.json - The problem is that you need a root subdomain for this and can't use paths.
I don't know what this does when the repository is implicit like 'image: docker.io/organization/image' and the same for gcr, quay et.c.

**Additional context**
Right now we're using Harbor as a caching server for dockerhub. (Dockerhub is the only repository we're having trouble with àt the moment.) This makes the cache have an address of registry.ourdomain.io/dockerhub-proxy and thus cannot be used without adding a reverse proxy to remove the path for the dockerconfig.

I've successfully added (not pretty mind you) text like this to the templates
```
tee -a compliantkubernetes-apps/helmfile/values/kube-prometheus-stack-sc.yaml.gotmp << EOF
### Added ###
prometheusOperator:
  admissionWebhooks:
    patch:
      image:
        repository: {{ .Values.global.docker_repository }}jettech/kube-webhook-certgen
EOF
```
...and the corresponding value in the config
`yq w --inplace .ck8s/clustername/sc-config.yaml global.docker_repository 'registry.ourdomain.io/dockerhub-proxy/'`

**Definition of done:**
When you can control the repositories to pull images from.
