### ISSUE TITLE
1 User alertmanager does not pass strictest safeguards

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#686]
**Describe the bug**

We started adding various [safeguards](https://elastisys.io/compliantkubernetes/user-guide/safeguards/). They seem to mostly work, except user-alertmanager cannot start (see error message below).

**To Reproduce**

Install apps using the following configuration:
```yaml
opa:
  imageRegistry:
    enforcement: deny
    URL:
      - harbor.ckdemo.a1ck.io
      - quay.io/jetstack/cert-manager-acmesolver
  networkPolicies:
    enforcement: deny
  resourceRequests:
    enforcement: deny
```

**Expected behavior**

User alertmanager starts without error.

**Screenshots**
```
level=error ts=2021-11-16T14:18:23.957111317Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"alertmanager/alertmanager\" failed: failed to create statefulset: admission webhook \"validation.gatekeeper.sh\" denied the request: [denied by require-harbor-repo] container \"alertmanager\" has an invalid image repo \"quay.io/prometheus/alertmanager:v0.21.0\", allowed repos are [\"harbor.ckdemo.a1ck.io\", \"quay.io/jetstack/cert-manager-acmesolver\"]\n[denied by require-harbor-repo] container \"config-reloader\" has an invalid image repo \"quay.io/prometheus-operator/prometheus-config-reloader:v0.48.1\", allowed repos are [\"harbor.ckdemo.a1ck.io\", \"quay.io/jetstack/cert-manager-acmesolver\"]\n[denied by require-networkpolicy] No matching networkpolicy found\n[denied by require-resource-requests] Container \"alertmanager\" has no cpu request"
```

**Version (add all relevant versions):**
 - Compliant Kubernetes apps v0.18.0

**Additional context**

I see two solutions to this problem.
1. We disable Gatekeeper for the alertmanager namespace.
2. We document what repos to allowlist (as we did for the acme resolver) and add requests to user-alertmanager
