### ISSUE TITLE
[2]Self service userAdmin creation

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#738]
**Is your feature request related to a problem? Please describe.**

For operators, it would be nice to just give one user to be `userAdmin` and then that person could add more people by themself.

**Describe the solution you'd like**

Give edit permission to something such that the `userAdmin` role can add more people to that role while at the same time not interfering with the `userAdmin` config in `wc-config`.

**Describe alternatives you've considered**

**Additional context**

**Definition of done:**
When could this feature be considered done.

* A `userAdmin` can add more `userAdmin` by themself without having access to the `wc-config.yaml` file

**Comment by cristiklein** [comment]
@Xartos Can you check if [this PR](https://github.com/elastisys/compliantkubernetes/pull/306) closes this issue?

**Comment by OlleLarsson** [comment]
I don't think it will.
In the example that you show over in the docs, the user wouldn't really be a "userAdmin" in the sense that it won't be bound the in clusterrolebinding for `user-view`, so it's not possible to list nodes or namespaces clusterwide.

**Comment by cristiklein** [comment]
Good point @OlleLarsson ! I just checked and I don't think we can delegate `user-view`. Even if I add the following to `user-view`:

```yaml
- apiGroups:                                                                    
  - rbac.authorization.k8s.io                                                   
  resources:                                                                    
  - clusterroles                                                                
  - clusterrolebindings                                                         
  verbs:                                                                        
  - get                                                                         
  - watch                                                                       
  - list        
```

I still get:

```console
$ kubectl apply -f extra-admin.yaml 
Error from server (Forbidden): error when creating "extra-admin.yaml": clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "cristian.klein@elastisys.com" cannot create resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
```

(Duh!!! :smile:)

I see three options:

1. Document that `user-view` delegation is not possible and is a known limitation.
2. Allow users to edit the `user-view` ClusterRoleBinding. I didn't test, but [privilege escalation prevention](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#privilege-escalation-prevention-and-bootstrapping) should make this safe.
3. Bind the `system:authenticated` group to the `user-view` ClusterRole. This is a bit more than one would usually give, but feels safe.

@OlleLarsson @Xartos What do you think?

**Comment by Xartos** [comment]
I would lean towards option 2 then. As long as we do some test and make sure that this is safe.

**Comment by OlleLarsson** [comment]
I would probably also lean towards 2.

**Comment by cristiklein** [comment]
Thanks @Xartos and @OlleLarsson! I found the following solution:

- compliantkubernetes-apps creates -- but does not update -- an `extra-user-view` ClusterRoleBinding
- the superusers are allowed to edit the `extra-user-view` ClusterRoleBinding
- privilege escalation prevents from using the ClusterRoleBinding to bind to more privileged ClusterRoles, like `admin`

The end result looks like this:

## Admin-side

```yaml
# user-admin-cluster-wide-delegation.yaml

# Managed by compliantkubernetes-apps
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-admin-cluster-wide-delegation
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  resourceNames:
  - extra-user-view
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
# Managed by compliantkubernetes-apps
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-admin-cluster-wide-delegation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-admin-cluster-wide-delegation
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: cristian.klein@elastisys.com
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: lars.larsson@elastisys.com
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin@example.com
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: disabled
---
# Created, but not updated by compliantkubernetes-apps
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extra-user-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-view
```

```console
admin$ kubectl apply -f user-admin-cluster-wide-delegation.yaml 
clusterrole.rbac.authorization.k8s.io/user-admin-cluster-wide-delegation unchanged
clusterrolebinding.rbac.authorization.k8s.io/user-admin-cluster-wide-delegation unchanged
clusterrolebinding.rbac.authorization.k8s.io/extra-user-view configured
```

## User-side

```yaml
# extra-workload-admin.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: extra-workload-admin
  namespace: demo1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: ci-cd
  namespace: demo1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extra-user-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-view
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: ci-cd
  namespace: demo1
  ```
  
  ```yaml
# illegal-extra-workload-admin.yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extra-user-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: ci-cd
  namespace: demo1
```

```console
user$ kubectl apply -f extra-workload-admin.yaml 
rolebinding.rbac.authorization.k8s.io/extra-workload-admin configured
clusterrolebinding.rbac.authorization.k8s.io/extra-user-view configured
```

```console
user$ kubectl apply -f illegal-extra-workload-admin.yaml 
Error from server (Forbidden): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"rbac.authorization.k8s.io/v1\",\"kind\":\"ClusterRoleBinding\",\"metadata\":{\"annotations\":{},\"name\":\"extra-user-view\"},\"roleRef\":{\"apiGroup\":\"rbac.authorization.k8s.io\",\"kind\":\"ClusterRole\",\"name\":\"admin\"},\"subjects\":[{\"apiGroup\":\"\",\"kind\":\"ServiceAccount\",\"name\":\"ci-cd\",\"namespace\":\"demo1\"}]}\n"}},"roleRef":{"name":"admin"},"subjects":[{"apiGroup":"","kind":"ServiceAccount","name":"ci-cd","namespace":"demo1"}]}
to:
Resource: "rbac.authorization.k8s.io/v1, Resource=clusterrolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding"
Name: "extra-user-view", Namespace: ""
for: "illegal-extra-workload-admin.yaml": clusterrolebindings.rbac.authorization.k8s.io "extra-user-view" is forbidden: user "cristian.klein@elastisys.com" (groups=["system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:[""], Resources:["bindings"], Verbs:["get" "list" "watch"]}
[...]
```

# Delegate-side

Before applying the ClusterRolebinding:

```console
sa$ kubectl get ns
Error from server (Forbidden): namespaces is forbidden: User "system:serviceaccount:demo1:ci-cd" cannot list resource "namespaces" in API group "" at the cluster scope
```

After applying the ClusterRolebinding:

```console
sa$ kubectl get ns
NAME                STATUS   AGE
alertmanager        Active   9d
cert-manager        Active   9d
default             Active   9d
demo1               Active   9d
demo2               Active   9d
demo3               Active   9d
falco               Active   9d
fluentd             Active   9d
gatekeeper-system   Active   9d
ingress-nginx       Active   9d
kube-node-lease     Active   9d
kube-public         Active   9d
kube-system         Active   9d
monitoring          Active   9d
rook-ceph           Active   9d
velero              Active   9d
```
