### ISSUE TITLE
Safeguard: Do not allow tolerations in user namespaces

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#762]
**Is your feature request related to a problem? Please describe.**

We have all kinds of safeguards in place, to ensure application developers don't compromise platform security and stability due to trivial mistakes. Currently, we place no restrictions regarding tolerations in user namespaces. This means that users can accidentally run Pods on Kubernetes control plane Nodes or Nodes reserved for additional services.

**Describe the solution you'd like**

```yaml
opa:
  taintTolerations:
    enforcement: deny  # default dryrun
    restrictedTaintToleration:
    - key: node-role.kubernetes.io/master
    - { key: nodeType, value: database }
```

Should trigger an error if a Pod with given tolerations is created in a user namespace, i.e., a namespace without the `owner: operator` label.

**Describe alternatives you've considered**

* Not implementing the present solution.
* Issuing recommendations via public docs

**Additional context**

* From the user's perspective, the feature should feel similar to [this safeguard](https://elastisys.io/compliantkubernetes/user-guide/safeguards/enforce-trusted-registries/)
* This [OPA policy](https://github.com/stackrox/blog-examples/blob/master/code/opa-gatekeeper-taint-tolerations/constraint.yaml) might be useful as a starting point.

**Definition of done:**

* Compliant Kubernetes supports the above configuration (please include a screenshot as evidence).
* Public docs are updated accordingly.
