### ISSUE TITLE
Safeguard: Enforce min and max number of replicas

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#764]
**Is your feature request related to a problem? Please describe.**

We have all kinds of safeguards in place, to ensure application developers don't compromise platform security and stability due to trivial mistakes. Currently, we place no restrictions regarding number of replicas. This means that users can accidentally run Deployments with insufficient replication.

**Describe the solution you'd like**

```yaml
opa:
  minMaxReplicas:
    enforcement: deny  # default dryrun
```

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    replicas-min: "4"
    replicas-max: "10"
  name: demo1
```

Should trigger an error if a Deployment in the annotated Namespace has a number of replicas which does not respect the Namespace's annotation.

**Describe alternatives you've considered**

* Not implementing the present solution.

**Additional context**

* From the user's perspective, the feature should feel similar to [this safeguard](https://elastisys.io/compliantkubernetes/user-guide/safeguards/enforce-trusted-registries/)
* This [OPA policy](https://www.magalix.com/blog/enforcing-a-minimum-and-maximum-number-of-kubernetes-pod-replicas-using-opa) might be useful as a starting point.

**Definition of done:**

* Compliant Kubernetes supports the above configuration (please include a screenshot as evidence).
* Public docs are updated accordingly.
