### ISSUE TITLE
Safeguard: Require labels

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#765]
**Is your feature request related to a problem? Please describe.**

We have all kinds of safeguards in place, to ensure application developers don't compromise platform security and stability due to trivial mistakes. Compliant Kubernetes should have the possibility to enforce required labels on various Kubernetes resources in user namespaces.

**Describe the solution you'd like**

Basically [this](https://elastisys.com/enforcing-policy-as-code-using-opa-and-gatekeeper-in-kubernetes/).

```yaml
opa:
  requiredLabels:
    enforcement: deny  # default dryrun
    requiredLabels:
    - match:
        kinds:
        - apiGroups: [""]
          kinds: ["Deployment", "Pod", "Service", "Ingress", "ConfigMap", "Secret", "PersistentVolume"]
        namespaces:
        - demo1
        - demo2
      labels:
      # Consider the following recommended labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels
      - app.kubernetes.io/created-by
      - app.kubernetes.io/name
      - app.kubernetes.io/instance
      - app.kubernetes.io/version
```

**Describe alternatives you've considered**

* No offering this feature.
* Offering this feature, but requiring manually created `K8SRequireLabel` objects.
* Offering this feature via the usual `opa` key.

**Definition of done:**

* Compliant Kubernetes supports the above configuration (please include a screenshot as evidence).
* Public docs are updated accordingly.
