### ISSUE TITLE
[2] Support DNS01 challenge

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#841]
**Is your feature request related to a problem? Please describe.**

Some customers might ask us to completely allowlist the SC, i.e., both HTTPS and HTTP (ACME). This is not a problem for UpTime monitoring, which [publish their IP addresses](https://uptimerobot.com/inc/files/ips/IPv4andIPv6.txt). However, this is problematic for LetsEncrypt, which doesn't publish source IPs for [HTTP01](https://community.letsencrypt.org/t/feature-request-list-of-source-ips-used-in-http-01-challenge/110784).

A solution to this is allowing DNS01 challenges.

**Describe the solution you'd like**

Example solution, please think of a configuration schema as part of this task:

```yaml
# sc-config.yaml
issuers:
  letsencrypt:
    prod:
      solvers:
        # this solver handles example.org challenges
        # and uses explicit credentials
        - selector:
            dnsZones:
              - "example.org"
          dns01:
            route53:
              region: eu-central-1
              accessKeyID: AKIAIOSFODNN7EXAMPLE
```

```yaml
# secrets.yaml
issuers:
  secretAccessKeySecretRef: blah-blah
```

NOTE: DNS01 would only work on SC, since those Ingresses have admin-controlled domains. WC usually has user-controlled domains, hence we still need to use HTTP01.

**Describe alternatives you've considered**

* See https://github.com/elastisys/compliantkubernetes-apps/issues/840; the present feature allows a more strict security boundary around the SC.

**Definition of done:**

* I can configure ClusterIssuer on the SC with DNS01 challenge.
* Onboarding document is updated with how to create minimal AWS credentials for necessary Route53 access.
* Screenshots showing that this works, even if the SC is completely fenced off, e.g., via very restrictive SecurityGroups.
