### ISSUE TITLE
[1] Groups in user grafana not applied.

### ISSUE THREAD

**Issue by robinAwallace** [elastisys/compliantkubernetes-apps#846]
**Describe the bug**

The groups for the oidc for user grafana is not being applied. It works fine for ops grafana.

sc-config:
```yaml
user:
  grafana:
    oidc:
      scopes: profile email openid groups
      userGroups:
        grafanaAdmin: ck8sdevops@elastisys.com
prometheus:
  grafana:
    oidc:
      userGroups:
        grafanaAdmin: ck8sdevops@elastisys.com
      scopes: profile email openid groups
```
User grafana
![image](https://user-images.githubusercontent.com/12862587/154911408-8ddfb6f2-88b8-46be-aaf8-702be1b2db26.png)

Ops grafana
![image](https://user-images.githubusercontent.com/12862587/154911438-911f39d3-efb8-4d00-8b2a-2b43cc6e1fdc.png)

**To Reproduce**
1. Checkout v0.19.0
2. Apply user-grafana with groups
3. Log into user-grafana as admin and look att settings and find that groups are not applied. 
4. Log into user-grafana as a user part of group and see that you do not receive the role. 

**Expected behavior**

Groups are used in user-grafana and the role is applied to users part of that group.

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.19.0

**Additional context**
