### ISSUE TITLE
Allow users to list pods and get metrics cluster-wide

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#850]
**Is your feature request related to a problem? Please describe.**
To allow users to easily determine resource allocation on nodes they need to be able to list pods cluster-wide in order to run `k describe node`.
Listing pods should not reveal any information that a user does not already have access to via Kibana and Grafana.

Being able to get metrics cluster-wide enables users to run `k top nodes` to quickly be able to determine resource usage exposed via the metrics-server.

**Describe the solution you'd like**
Users should be assigned the following cluster-wide permissions
```
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
```

Note that I'm not 100% sure if they need `list` and `watch` for the metrics or if it is enough with `get`.

**Describe alternatives you've considered**
Not giving users more privileges.

**Definition of done:**
A user  can run `k describe nodes` and see pods and allocated resources, and they can run `k top nodes` and see usage information.
