### ISSUE TITLE
[2] Falco: Add configuration to tune falco rules for each environment

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#889]
**Is your feature request related to a problem? Please describe.**

As discovered during the Falco alerting investigation, some alerts only show up in selected environments, due to unique -- but legitimate -- application behavior. For example, one of our environments features an SFTP server with produces [Terminal shell in container](https://github.com/elastisys/compliantkubernetes-apps/blob/v0.19.1/helmfile/upstream/falco/rules/falco_rules.yaml#L1990).

**Describe the solution you'd like**
Let us start by exposing all `(never_true)` macros -- see example [here](https://github.com/elastisys/compliantkubernetes-apps/blob/v0.19.1/helmfile/upstream/falco/rules/falco_rules.yaml#L1987) in `wc-config.yaml`. Something like:

```yaml
falco:
  custom_rules:
    - macro: user_expected_terminal_shell_in_container_conditions
      condition: container.image.repository in ("docker.io/project/awesome-sftp-server")
```

Perhaps we only need to expose [`custom_rules`](https://github.com/elastisys/compliantkubernetes-apps/blob/v0.19.1/helmfile/upstream/falco/values.yaml#L338) with a lot of comments and examples.

**Describe alternatives you've considered**

* Ignore alerts in the on-call management tool.

**Additional context**

* See [arch meeting slides (private)](https://docs.google.com/presentation/d/1O4hkTmxeBXTaLZ94g3QnXsFkEZwg6xSu0OMyoTwVzqQ/edit#slide=id.g11956c970a7_0_5)

**Definition of done:**

* I can customize Falco alerting rules for each environment.
