### ISSUE TITLE
[2] Some config is damaged after init

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#955]
**Describe the bug**

When running init with this config in `wc-config.yaml`:

```yaml
velero:
  nodeSelector:
    elastisys.io/node-type: elastisys
```

It turns into this config in the `common-config.yaml`:

```yaml
velero:
  nodeSelector:
    elastisys:
      io/node-type: {}
```

**To Reproduce**
1. Add the config above
2. Run init
3. See error

**Expected behavior**
The config should stay in place

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.20.1

**Additional context**.
